### ISSUE TITLE
Does not work in version 2.47

### ISSUE THREAD

**Issue by Havokdan** [Rookiestyle/EarlyUpdateCheck#12]
## Overview
Version 2.47 came out and I realized that the plugin does not work on it when Keepass is installed in "Program Files" and works when installed "Program Files (x86)".

## Steps to Reproduce
Install in the folders "Program Files" and try to update any plugin.

## Expected Behavior
The update function should appear available, however, in the current state, only the update check is working.

**Comment by Rookiestyle** [comment]
For me, this is working. I installed KeePass 2.47 in `C:\Program Files`with all plgx files directly inside the Plugins folder

Please describe a bit more in detail what is not working - no button to start the upgrade, no UAC prompt, error messages?
Please also attach a [debug file](/Rookiestyle/EarlyUpdateCheck/wiki/Create-a-debugfile)

**Comment by Havokdan** [comment]
The button to update the plugins does not appear, even when there is update.

**Comment by Rookiestyle** [comment]
[(Where is `ExternalPluginUpdates.xml` located?](/Rookiestyle/EarlyUpdateCheck/wiki/Update-other-plugins#how-to-update-other-plugins)

> Please also attach a [debug file](/Rookiestyle/EarlyUpdateCheck/wiki/Create-a-debugfile)
When creating the debug file, please do it while starting KeePass: https://github.com/Rookiestyle/EarlyUpdateCheck/wiki/Create-a-debugfile#startup-parameter
Only this way, the file will contain all required information

**Comment by Havokdan** [comment]
[Debug_EarlyUpdateCheck_20210122T171452Z.zip](https://github.com/Rookiestyle/EarlyUpdateCheck/files/5857599/Debug_EarlyUpdateCheck_20210122T171452Z.zip)

**Comment by Rookiestyle** [comment]
According to the file, you already updated to KPEnhancedEntryView 2.3.1?

Nevertheless, please do the following to help me narrow down the issue:

1. Use the attached debug build of EarlyUpdateCheck
2. Optional: Downgrade to KPEnhancedEntryView 2.3
3. Restart KeePass
4. Do update check
5. Close KeePass
6. Attach the new debug file and tell me where ExternalPluginUpdates.xml is located
[EarlyUpdateCheck.zip](https://github.com/Rookiestyle/EarlyUpdateCheck/files/5857912/EarlyUpdateCheck.zip)


The info about other author's plugins is loaded during KeePass start and debug mode needs to be active to to add this part to the debug file.
The attached debug build of EarlyUpdateCheck has debug mode active, this way you don't have to start KeePass using commandline parameters

It also changes collecting installed plugins and adds more verbose debug info that hopefully helps

**Comment by Havokdan** [comment]
[Debug_EarlyUpdateCheck_20210122T200715Z.zip](https://github.com/Rookiestyle/EarlyUpdateCheck/files/5858331/Debug_EarlyUpdateCheck_20210122T200715Z.zip)
I used windows search but didn't find the ExternalPluginUpdates.xml

**Comment by Rookiestyle** [comment]
C:\Program Files\KeePass Password Safe 2\Plugins\ExternalPluginUpdates.xml
This is where the file is expected.

Please read https://github.com/Rookiestyle/EarlyUpdateCheck/wiki/Update-other-plugins 
EarlyUpdateCheck can update

**Comment by Havokdan** [comment]
Well, I think I'll do it the hard way, I'll uninstall Keepass, delete the traces, kill only the database and reinstall.

**Comment by Rookiestyle** [comment]
That's up to you, you definitely don't have to. Downloading EarlyUpdateCheck and optionally ExternalPluginUpdates.xml (to update the plugins listed inside) would work as well.
