### ISSUE TITLE
Add the ability to update .lngx translations files

### ISSUE THREAD

**Issue by hauk92** [Rookiestyle/EarlyUpdateCheck#15]
## Summary
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Provide a brief overview of what the new feature is all about)
Add the ability to update already installed .lngx translations files from https://keepass.info/translations.html
Translations are hosted on sourceforge https://sourceforge.net/projects/keepass/files/Translations%202.x/ but not all translations  are updated to the latest version so it should make sense to get the version information from the KeePass site.

## Added value
[NOTE]: # (Describe how you and other users would benefit from this feature)
Currently there is no update check or (semi-)auto update for language files, this feature would simplify updating KeePass (translations) for non english users a lot.

**Comment by Rookiestyle** [comment]
Language names shown in the language window don't neccessarily relate to their lngx file names, e. g. *"Chinese_Simplified (简体中文)"* and *Chinese_Simplified.lngx*
Sometimes they even don't match to the zip filename on the download page
* zip file: French.zip or French-b.zip or French-c.zip
* lngx file: French.lngx
* language name: French (Français)

There is no clear answer on what to do if you e. g. use the french translation from 2.46/KeePass-2.46-French-c.zip but in the 2.47 only French.zip ans French-b.zip were available.
Download French.zip? Download French-b.zip? Don't download? What if e. g. French.zip is downloaded and the next day a French-c.zip is released?

In addition the file itself is a "moving target". Not every translation is available in every KeePass version folder in the Translations folder.
So, if you're using KeePass 2.46 (there are quite a lot users who don't update asap), I would need to
* ignore the 2.47 translation folder
* try downloading 2.46/KeePass-2.46-Portuguese_PT.zip
* fail and interpret the http error code
* try downloading 2.45/KeePass-2.45-Portuguese.zip
* pay the 5s waiting time fee before the download starts
* Do all this every time you click the "Update lngx files whether they changed or not" button (yes, the lngx file can be updated and no additional file will be released)

While I like the idea as such, I don't think this can be done in an efficient way that does not result in a lot of confusion no matter how exactly my plugin will answer all those "what if" questions

**Comment by hauk92** [comment]
Thank you for considering! I agree the naming is suprisingly inconsistent/complicated.
There is a KeePass [feature request](https://sourceforge.net/p/keepass/feature-requests/499/) in which checking for translation updates is mentioned.


> So, if you're using KeePass 2.46 (there are quite a lot users who don't update asap), I would need to
> 
> * ignore the 2.47 translation folder
> * try downloading 2.46/KeePass-2.46-Portuguese_PT.zip
> * fail and interpret the http error code
> * try downloading 2.45/KeePass-2.45-Portuguese.zip
> * pay the 5s waiting time fee before the download starts
> * Do all this every time you click the "Update lngx files whether they changed or not" button (yes, the lngx file can be updated and no additional file will be released)

And what if the file is named KeePass-2.45-Portuguese-b.zip? :D
