### ISSUE TITLE
Add the ability to update ExternalPluginUpdates.xml

### ISSUE THREAD

**Issue by hauk92** [Rookiestyle/EarlyUpdateCheck#16]
## Summary
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Provide a brief overview of what the new feature is all about)
One-click updating ExternalPluginUpdates.xml to add new (or fix) one-click updatable plugins would be very nice!
Specifying the source of ExternalPluginUpdates.xml would also be a nice feature (possibly in ExternalPluginUpdates.xml itself).

**Comment by Rookiestyle** [comment]
As every user can update this file for himself, making this part of One-click update would mean to have two files
* ExternalPluginUpdates.xml which is downloaded if a new version is published
* ExternalPluginUpdatesUser.xml which contains additional plugins' information and a flag to exclude certain plugins from One-click update
   * might be you need to run version 5 of a plugin as starting with version 6 of the plugin, it won't work on your device
  * would be bad, if a new ExternalPluginUpdates.xml would make this part of One-click update and you have to deselect it manually every time

Is that what you're asking for?





> Specifying the source of ExternalPluginUpdates.xml would also be a nice feature (possibly in ExternalPluginUpdates.xml itself).

This one I don't get, especially the parts in brackets.
The reason for the current location for this file is explained in the security chapter here: https://keepass.info/help/v2/plugins.html
Making this configurable would add a certain risk, not to mention hat telling EarlyUpdateCheck to read file xyz to know where file xyz is stored won't work - if that's what you mean with "possibly in ExternalPluginUpdates.xml itself"

**Comment by hauk92** [comment]
Yes or you could just opt out of updating ExternalPluginUpdates.xml. What additional plugin information would be needed in ExternalPluginUpdatesUser.xml?
Sorry the second part was just meant to be update URL for ExternalPluginUpdates.xml so for example

`https://raw.githubusercontent.com/hauk92/EarlyUpdateCheck/master/ExternalPluginUpdates/ExternalPluginUpdates.xml`

instead of 

`https://raw.githubusercontent.com/Rookiestyle/EarlyUpdateCheck/master/ExternalPluginUpdates/ExternalPluginUpdates.xml`
