### ISSUE TITLE
Support multiple item extraction from zip files.

### ISSUE THREAD

**Issue by lucknaumann** [Rookiestyle/EarlyUpdateCheck#21]
## Summary
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Provide a brief overview of what the new feature is all about)

Support all items in a zip file to be extracted.
Support certain items within a zip file to be extracted.

Some zip files contain multiple items, including an entire folder. Currently, there is no command to extract these items.

## Added value
[NOTE]: # (Describe how you and other users would benefit from this feature)

Users would be able to update more plugins with EarlyUpdateCheck, the [Ketarin](https://www.ketarin.org/) of KeePass plugins! 😄 

## Example
[NOTE]: # (Show a picture or a mock-up if applicable)

- [IOProtocolExt](https://keepass.info/plugins.html#ioprotocolext) extracts a folder "**IOProtocolExt_WinSCP**," a "**IOProtocolExt.plgx**" and "**IOProtocolExt.dll**" file, as well as a "**IOProtocolExt_ReadMe.html**" file (OK, probably less important!), all to the plugins folder. [Download](https://keepass.info/extensions/v2/ioprotocolext/IOProtocolExt-1.16.zip)
- [KeePassNatMsg](https://keepass.info/plugins.html#keepassnatmsg) extracts a folder, "**KeePassNatMsg**," with 3 dll files in it, where the **entire folder** is placed in the plugins folder. [Download](https://github.com/smorks/keepassnatmsg/releases/download/v2.0.11/KeePassNatMsg-v2.0.11-binaries.zip)

**Comment by Rookiestyle** [comment]
Ading the ability to define this on file level would add to much complexity, something like this won't be implemented:
* file_1.dll
* file_2.plgx
* folder_1/file_1.dll
* folder_2/file_3.plgx

I can think of a ZipExtractAll approach and simply take everything that is contained in the zip file.
Not yet sure what needs to be considered, to e. g. avoid overwriting something that shall not be overwritten.

**Comment by Rookiestyle** [comment]
Two concerns where I need to further think about:

* How to handle files that were extracted from the version 1 zip but that do no longer exist in the version 2 zip file?
* If it's a "keep" it might cause issues and would require manual actions to resolve that
* If it's a delete the question is how to know which files need to be deleted?

For the last topic: Imagine a user not using the KeePassNatMsg folder but putting the dll files right into the Plugins folder. Would be pretty bad if I delete all other plugins when updating KeePassNatMsg in this case

Comments are welcome while I think about this more in detail

**Comment by lucknaumann** [comment]
Thanks for your response and consideration. I was thinking of the ZipExtractAll option. It would be ridiculous to do anything else. 😄 

In terms of any issues with a plugin, it would be the user's responsibility to track that down by going to the plugin's site to find out why. From what I can recall, these plugins haven't changed in their implementation, but that doesn't mean they won't.

**Comment by lucknaumann** [comment]
Thanks so much for doing this! 😀
