### ISSUE TITLE
Updating KeePassNatMsg via ZipExtractAll leads to silent KeePass crashes

### ISSUE THREAD

**Issue by hauk92** [Rookiestyle/EarlyUpdateCheck#22]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)
Updating KeePassNatMsg via ZipExtractAll leads to silent KeePass crashes and wrong files/folders in the "\KeePass Password Safe 2\Plugins\" folder.

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Intall an old version of KeePassNatMsg
2. Update via one-click plugin update
3. Restart KeePass

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)
All plugin files are updated and KeePass (re)starts.

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)
KeePass silently crashes and will not launch until manually deleting the files in the plugin folder.

Folder and files before update:
```
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\KeePassNatMsg.dll
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\Mono.Posix.dll
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\Newtonsoft.Json.dll

```

Folders and files after update:
```
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\KeePassNatMsg
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\KeePassNatMsg.dll (new)
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\Mono.Posix.dll (old)
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\Newtonsoft.Json.dll (old)
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\KeePassNatMsg\KeePassNatMsg.dll (old)
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\KeePassNatMsg\Mono.Posix.dll (old)
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\KeePassNatMsg\KeePassNatMsg\Newtonsoft.Json.dll (old)
```

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 10
KeePass Version: Current
Plugin Version: Current
XML entry:
```
<UpdateInfoExtern>
	<PluginName>KeePassNatMsg</PluginName>
	<PluginURL>https://keepass.info/plugins.html#keepassnatmsg</PluginURL>
	<PluginUpdateURL>https://github.com/smorks/keepassnatmsg/releases/latest/download/KeePassNatMsg-v{MAJOR}.{MINOR}.{BUILD}-binaries.zip</PluginUpdateURL>
	<UpdateMode>ZipExtractAll</UpdateMode>
	<AllowVersionStripping>False</AllowVersionStripping>
</UpdateInfoExtern>
```
[Debug_EarlyUpdateCheck_20210305T141142Z.zip](https://github.com/Rookiestyle/EarlyUpdateCheck/files/6091145/Debug_EarlyUpdateCheck_20210305T141142Z.zip)

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
I will provide a fix soon.

**Comment by Rookiestyle** [comment]
The new release fixes this bug and no additional folders are created.

Since KeePassNatMsg is shipped as dll, additional restrictions apply: https://github.com/Rookiestyle/EarlyUpdateCheck/wiki/One-click-plugin-update#updating-dll-plugin-files
