### ISSUE TITLE
Add KeeTheme

### ISSUE THREAD

**Issue by theincogtion** [Rookiestyle/EarlyUpdateCheck#26]
## Summary
Add KeeTheme

## Added value

```
<UpdateInfoExtern>
		<PluginName>KeeTheme</PluginName>
		<PluginURL>https://keepass.info/plugins.html#keetheme</PluginURL>
		<PluginUpdateURL>https://github.com/xatupal/KeeTheme/releases/latest/download/KeeTheme.plgx</PluginUpdateURL>               
		<UpdateMode>PlgxDirect</UpdateMode>
		<AllowVersionStripping>False</AllowVersionStripping>
</UpdateInfoExtern>
```

I was not able to update the file :)
https://github.com/Rookiestyle/EarlyUpdateCheck/blob/master/ExternalPluginUpdates/ExternalPluginUpdates.xml

**Comment by Rookiestyle** [comment]
KeeTheme is offered as plgx and as dll.
For user of the dll version, adding the data above will cause issues.

I propose to create a file *ExternalPluginUpdatesUser.xml* in the same folder as the already existing file *ExternalPluginUpdates.xml* with this content.

Let me know whether this works for you.
```
<?xml version="1.0" encoding="utf-8"?>
<!--
This file is _not_ part of EarlyUpdateCheck's one-click update

It MUST NOT contain a version tag

It can be used to add / change update information, e. g. for plugins
available in your local network (private, office, ...)
It can also be used to exclude plugins from one-click update
-->
<UpdateInfoExternList>
	<!-- Example for additional plugins -->
	<!--
	<UpdateInfoExtern>
		<PluginName>My plugin</PluginName>
		<PluginURL>https://localhost/myplugin</PluginURL>
		<PluginUpdateURL>https://localhost/myplugin/download/myplugin.plgx</PluginUpdateURL>
		<UpdateMode>PlgxDirect</UpdateMode>
		<AllowVersionStripping>True</AllowVersionStripping>
	</UpdateInfoExtern>
	-->
	<UpdateInfoExtern>
		<PluginName>KeeTheme</PluginName>
		<PluginURL>https://keepass.info/plugins.html#keetheme</PluginURL>
		<PluginUpdateURL>https://github.com/xatupal/KeeTheme/releases/latest/download/KeeTheme.plgx</PluginUpdateURL>               
		<UpdateMode>PlgxDirect</UpdateMode>
		<AllowVersionStripping>False</AllowVersionStripping>
	</UpdateInfoExtern>
	
	<!-- Example for plugin to ignore -->
	<!--
	<UpdateInfoExtern>
		<PluginName>Some other plugin</PluginName>
		<Ignore />
	</UpdateInfoExtern>
	-->
</UpdateInfoExternList>
```

**Comment by theincogtion** [comment]
@Rookiestyle I couldn't find such a file in the appdata or keepass folder

**Comment by Rookiestyle** [comment]
You placed the file in the correct location as it shows KeeTheme on your screenshot.
KeePass checks for updates only once per day. You can manually check for updates in KeePass' help menu.

If KeeTheme is shown as *new version available*, but no update option is given please do the following:
* Activate debug mode as described here: https://github.com/Rookiestyle/EarlyUpdateCheck/wiki/Create-a-debugfile 
* Perform the update check
* Close Kee Pass
* Add the created debug file here

**Comment by theincogtion** [comment]
Thanks worked fine :)
I thought it checks on every keepass start.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> I thought it checks on every keepass start.

Yes, the Plugin Readme says so?

> "Check for update at KeePass startup" is active

There is an option to check Update KeePass on startup (not plugin option). You may need to check this too!
