### ISSUE TITLE
Plugin do not work correctly when running KeePass using Mono

### ISSUE THREAD

**Issue by RichardBeisser** [Rookiestyle/EarlyUpdateCheck#31]
Hello,
I am using Keepass on a debian based Linux (Raspian) with mono.
Then I start Keepass with your plugin the first time a day, the plugin is looking for Updates
But while/after searching for Updates,

![searching](https://user-images.githubusercontent.com/47367173/138120126-a0bd6b39-c452-43d6-bbda-dfd715a97fce.png)

 KeePass crashes with this error message

![Bildschirmfoto vom 2021-10-08 12-13-55](https://user-images.githubusercontent.com/47367173/138119366-3fa42086-78fd-484e-b2bd-67840987f64b.png)
:

**Comment by RichardBeisser** [comment]
> Does this happen only once per day or everytime you run the update check?

It only happens when doing the update check when starting KeePass.
Because the plugin does this only while first run a day of KP, it only happens one time a day.

When you start the update check within the running KP, There is no error.

How can I force the plugin to make a update check again  on a day?

**Comment by Rookiestyle** [comment]
Closed due to missing feedback.

I'll reopen this issue if feedback is provided.
