### ISSUE TITLE
Support updating DLL Plugins

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Rookiestyle/EarlyUpdateCheck#37]
## Summary

> There is no way for my plugin to download the newest version in only one step. You also need to manually replace your ... files ... as dll ... and you can't delete dll files while they are loaded.
> 

You can NOT delete a used  DLL plugin file or overwrite it.

## Added value
There is a workaround for the loaded DLL file auto updating.

## Example
But you can actually rename it to let's say `RuleBuilder.dll.bak` and download new RuleBuilder.dll at the same location. Next KeePass startup, the updated version will be loaded. ;) `RuleBuilder.dll.bak` can be deleted next start, as the file should be ignored by KeePass, not recognized as Plugin.

Also, moving the loaded DLL is possible. So you could move any loaded Plugin to be updated into a /PendingDelete directory, append `.bak` to filename (to make sure it will not be loaded again) and on every EarlyUpdateCheck startup, delete or empty that directory if present.

This could be useful for upgrading any DLL based Plugins, I guess.

**Comment by Rookiestyle** [comment]
I'll have a look at that, thanks for the hint

**Comment by Rookiestyle** [comment]
Next version of EarlyUpdateCheck will try to delete the old plugin files as today.
If this fails, it'll try to move them to the user's temporary folder.

This basically works, just need to doublecheck that it also works if the plugin directory is write protected (Windows UAC, ...)
