### ISSUE TITLE
Unsupported Plugin KeePass Pronounceable Password Generator 🧩

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Rookiestyle/EarlyUpdateCheck#44]
## Overview
Version info missing for Plugin "KeePass Pronounceable Password Generator"

Is it not supported, due to missing version information? Does it need to be removed?

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Started update check with version v1.0.4
2. I see ![Pronounceable](https://user-images.githubusercontent.com/46166740/144418094-7d505841-273d-41bb-9338-81f76f541b1e.png)
3. but latest should be v1.0.4**b**
https://sourceforge.net/projects/pronouncepwgen/files/pronouncepwgen/1.0.4b/

## Expected Behavior
allow update to v1.0.4b

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)
shows question Marks 

## Context
[NOTE]: # (Provide any additional information you may have)
OS: win11
KeePass Version: 2.49
Plugin Version: 3.5

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
> Is it not supported, due to missing version information?

Yes

> Does it need to be removed?

No need to remove it, I'll leave it in to avoid the need of changing the file again


> but latest should be v1.0.4b
I'm not sure whether the newest version will be shown as 1.0.4b in KeePass update check
