### ISSUE TITLE
I can't find ExternalPluginUpdates.xml, and I think the EarlyUpdateCheck is not working because of that.  Apparently, downloading the Early UpdateCheck should give me these 2 files, but it only gave me the EarlyUpdateCheck.plgx

### ISSUE THREAD

**Issue by 1998vss** [Rookiestyle/EarlyUpdateCheck#47]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)

## Context
[NOTE]: # (Provide any additional information you may have)
OS: 
KeePass Version:
Plugin Version:

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
ExternalPluginUpdates.xml is not required to update any of my plugins.
It is only required to update other developers' plugins and as of now it is optional and up to you as user to download the file.
This is described in the wiki: https://github.com/Rookiestyle/EarlyUpdateCheck/wiki/Update-other-plugins#how-to-update-other-plugins
> To get started, you might want to use ExternalPluginUpdates.xml located in folder ExternalPluginUpdates of this repository. Download it here

If you're issue is about a different topic, please provide more details incljuding a [debug file](https://github.com/Rookiestyle/EarlyUpdateCheck/wiki/Create-a-debugfile#how-to-create-a-debugfile) and I'll reopen this issue.


I'm working on an option to ask the user whether ExternalPluginUpdates.xml should be downloaded if it does not exist all.
This will take some time as I'm pretty busy currently.

**Comment by 1998vss** [comment]
Hey, thx for before, but I'm a tech newbie here and I'm confused, because the "here" button gives me this page: https://raw.githubusercontent.com/Rookiestyle/EarlyUpdateCheck/master/ExternalPluginUpdates/ExternalPluginUpdates.xml

What should I do with it?

**Comment by Rookiestyle** [comment]
Wiki:
> All required information is read from a file named ExternalPluginUpdates.xml which has to be placed in the plugin folder.

This is where you need to save file that the "here" button shows.
In case you don't know how to locate the plugin folder, you can go `Tools -> Plugins... -> Open Folder`


Or - as an alternative - you wait 1-2 days. I think I can release a new version of EarlyUpdateCheck by then that will do that for you.
