### ISSUE TITLE
Alternative method not showing UAC

### ISSUE THREAD

**Issue by gabriele-v** [Rookiestyle/EarlyUpdateCheck#52]
Hello,
I have an issue updating some plugins (in this case KeePassOTP) with EarlyUpdateCheck.

If I select KeePassOTP and then click UpdatePlugins, I have this message:
![image](https://user-images.githubusercontent.com/7106290/205434730-47005281-54aa-494e-bfe1-b611c560c49a.png)

Choosing yes, no UAC window is shown and I'm unable to close the EarlyUpdateCheck window, I have to kill KeePass from TaskManager.

Not sure if it's related, I'm using "Master Key on secure desktop" function, but EarlyUpdateCheck has the same behaviour even when run from Help -> Check for updates

Using Windows 11 22H2 Build 22621.819

**Comment by Rookiestyle** [comment]
I'm running the same Windows version and don't face this issue.

If you choose "No", will it open a folder containing the new files? Should be somewhere in your temp folder
If you disable "Master Key on secure desktop", does it change the result?

Please also try with the attached version.
It will show some more debug messages and also create a debug file. I'ld need this information to hopefully find something

[EarlyUpdateCheck.zip](https://github.com/Rookiestyle/EarlyUpdateCheck/files/10146208/EarlyUpdateCheck.zip)

**Comment by gabriele-v** [comment]
With "Master Key on secure desktop" disabled, it's working correctly.
Note that both times I've run it from Help -> Check for updates and not at startup.

I've run the debug version, it stucks after this message:
![image](https://user-images.githubusercontent.com/7106290/205438303-0360b57f-a383-49de-ae85-fe08450d2c91.png)

Last entry in the debug file is the following:
```
		<DebugEntry>
			<Message>Show info</Message>
			<Counter>1</Counter>
			<Severity>Info</Severity>
			<DateTimeUtc>20221203T111706Z</DateTimeUtc>
			<Parameters>
				<Param>Early Update Check</Param>
				<Param>Trying to move new files
From: C:\Users\gabri\AppData\Local\Temp\k44bcm5a.gw0\
To: C:\Program Files\KeePass Password Safe 2\Plugins\</Param>
			</Parameters>
			<StackFrames>
				<StackFrame>
					<Method>ShowInfo (PluginTools.Tools)</Method>
					<FileName />
					<Line>0</Line>
				</StackFrame>
				<StackFrame>
					<Method>MoveAllShieldified (EarlyUpdateCheck.PluginUpdateHandler)</Method>
					<FileName />
					<Line>0</Line>
				</StackFrame>
				<StackFrame>
					<Method>UpdatePlugins (EarlyUpdateCheck.EarlyUpdateCheckExt)</Method>
					<FileName />
					<Line>0</Line>
				</StackFrame>
				<StackFrame>
					<Method>bUpdatePlugins_Click (EarlyUpdateCheck.EarlyUpdateCheckExt)</Method>
					<FileName />
					<Line>0</Line>
				</StackFrame>
				<StackFrame>
					<Method>OnClick (System.Windows.Forms.Control)</Method>
					<FileName />
					<Line>0</Line>
				</StackFrame>
				<StackFrame>
					<Method>WndProc (System.Windows.Forms.Button)</Method>
					<FileName />
					<Line>0</Line>
				</StackFrame>
			</StackFrames>
		</DebugEntry>
```

**Comment by gabriele-v** [comment]
I don't think it's related to https://github.com/Rookiestyle/EarlyUpdateCheck/issues/49 because after the fix everything was fine. I've then upgraded to W11 and probably upgraded KeePass version, not sure where it may be the issue.

**Comment by Rookiestyle** [comment]
I did the following:

**Test 1**
Start KeePass having secure desktop enabled
Do not open any database
UAC prompt during plugin update is shown, no issues

**Test 2**
Start KeePass having secure desktop enabled
Open a database
UAC prompt during plugin update is not shown, facing the same issue as you

**Test 3**
Start KeePass having secure desktop enabled
Open a database 
Close database
UAC prompt during plugin update is not shown, facing the same issue as you

**Test 4**
Start KeePass having secure desktop enabled
Open a database 
Disable secure desktop
UAC prompt during plugin update is not shown, facing the same issue as you


It seems that showing the secure desktop once causes this issue, no matter what you do afterwards.
I don't think this is due to missing cleanups but suspect an issue within Windows.
Secure Desktop is using native Windows functions and so do I for [UAC copy mode](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shfileoperationa).

Only way for me to handle this, is to open the downloaded files in explorer instead of asking for UAC since even deactivating secure desktop does not prevent the issue

**Comment by gabriele-v** [comment]
I haven't looked entirely at your code but looks like you are using [SHFileOperation ](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shfileoperationa?redirectedfrom=MSDN) to copy files, what about update it (in case OS is at least Vista) to the newer [IFileOperation](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifileoperation) ?

**Comment by gabriele-v** [comment]
By the way, if the issue would be the first display of the secure desktop, it doesn't explain why this test is working:

Start KeePass having secure desktop enabled
Open a database and inserting master key on secure desktop
Close database
Reopen the same database, you can insert again master key on secure desktop

**Comment by Rookiestyle** [comment]
I'll have a look at IFileOperation, KeePass is STA and therefor it should work.


> By the way, if the issue would be the first display of the secure desktop, it doesn't explain why this test is working:
> 
> Start KeePass having secure desktop enabled Open a database and inserting master key on secure desktop Close database Reopen the same database, you can insert again master key on secure desktop

Secure desktop is creating additional desktops using native methods CreateDesktop, SwitchDesktop, ...
It looks like UAC but it is not UAC.
Whatever it does (or the underlying .NET/Windows) is different from UAC but it somehow prevents the UAC prompt to be shown from SHFileOperation

**Comment by Rookiestyle** [comment]
Using IFileOperation will make the plugin incompatible with *nix, I won't do that.

Instead, following fix will be implemented
* If key prompt or key creation form have been shown on secure desktop at least once, EarlyUpdateCheck will not use SHFileOperation
* Instead, the user is prompted to open the temp folder containing the downloaded files and move them to the right location manually
*  If key prompt or key creation form was not shown on secure desktop yet, EarlyUpdateCheck will show the UAC promp if required

**Comment by gabriele-v** [comment]
What about spawn a new process (IE copy.exe or something similar, not sure if there is anything cross-platform) with these parameters?
```
Process.StartInfo.UseShellExecute = true;
Process.StartInfo.Verb = "runas";
```

**Comment by Rookiestyle** [comment]
Well, technically this would work but...

There's two options:
1. I use an existing file and this would need to be cmd.exe as no other file allowing to copy files is guaranteed to exist
2. I have my own EarlyUpdateCheck_Copy.exe

Reg 1:
You seem to have some development bsckground, but pleae assume you are a regular computer user.
What would be your reaction to a screen like "Windows Command line tool wants to change your device"?
I'ld consider it fishy and would either ask my IT-savy nephew or - if at all - complain about KeePass starting arbitrary files

Reg 2:
This would mean either the user (manually) or I (automatically, after getting consent) need to download an executable file and run it on a user's desk.
Sounds even fishier imo ;)

Call it a design question/decision, but I won't show UAC prompts for running different executables that the user probably can't relate to KeePass.

Many thanks for making me aware of this topic and your suggestions but you (and others) need to copy files manually in that case.
I might consider a popup for you to confirm that you did that and trigger KeePass restart if you consider this helpful?

**Comment by gabriele-v** [comment]
I understand your concerns, I was just trying to find a solution\workaround because manual copy makes EarlyUpdateCheck a bit useless.

Last suggestion: what about show a pop up saying paste the file in the opened folder and after ok it will copy the source file in clipboard and automatically open plugins folder? I think it wuould make the copy process much easier.

**Comment by Rookiestyle** [comment]
> I understand your concerns, I was just trying to find a solution\workaround because manual copy makes EarlyUpdateCheck a bit useless.

You could deactivate "Masterkey on secure desktop" :)
After all, it's **not** UAC - although it still offers some kind of protection against e. g. "regular" key loggers

> Last suggestion: what about show a pop up saying paste the file in the opened folder and after ok it will copy the source file in clipboard and automatically open plugins folder? I think it wuould make the copy process much easier.

I like that approach and will try to implement that.
Hopefully this can be implemented, if not I can at least open both source/temp folder and target folder

**Comment by Rookiestyle** [comment]
Copying source files in clipboard works fine if it's only files w/out folders.

As soon as folders are involved it's still possible to copy everything but when doing [Ctrl] + [V] to paste the folder structure will be lost and everything is pasted right into the selected target folder.
Folders are used by quite some users to seperate plugins and their auxiliary files from each other and also I mysqlf use a *Translations* folder for translation files
