### ISSUE TITLE
Addition of "Title Display" plugin

### ISSUE THREAD

**Issue by ankrman** [Rookiestyle/EarlyUpdateCheck#55]
## Summary
Hi Rookiestyle,

I tried to add the plugin "Title Display". It's recognized/listed within your plugin but I don't get update alerts (I downloaded 1.3 and expected an "1.4 is available" alert). 

Or did I get something wrong and the whole update checking is relying on KeePass' own update check mechanism (described [here](https://keepass.info/help/v2_dev/plg_index.html#upd)) and just not corretly implemented by the dev of the plugin? At least it's not recognized within KeePass...

![image](https://user-images.githubusercontent.com/46501937/227714982-58fabaab-e159-4ebf-b52a-0cd66b4bf4c4.png)

Thanks in advance!

## Added value
Update alerts for all others using the plugin

## Example
```
	<UpdateInfoExtern>
		<PluginName>Title Display</PluginName>
		<PluginURL>http://gogogadgetscott.info/keepass/titledisplay/</PluginURL>
		<PluginUpdateURL>http://gogogadgetscott.info/keepass/titledisplay/TitleDisplay-{major}.{minor}.zip</PluginUpdateURL>
		<UpdateMode>ZipExtractPlgx</UpdateMode>
		<AllowVersionStripping>False</AllowVersionStripping>
	</UpdateInfoExtern>
```

**Comment by Rookiestyle** [comment]
> Or did I get something wrong and the whole update checking is relying on KeePass' own update check mechanism (described [here](https://keepass.info/help/v2_dev/plg_index.html#upd)) and just not corretly implemented by the dev of the plugin? At least it's not recognized within KeePass...

Your assumption is correct.
EarlyUpdateCheck relies on KeePass' own update check and the author of Title Display implemented support for update checking with version 1.4.

I will add your enhancement to my xml file, thanks for that
You need to upgrade to version 1.4 manually unfortunately.
Potential future versions of this addon will be identified by KeePass and thus EarlyUpdateCheck can ease updating to e. g. 1.5 whenever it will be released.
