### ISSUE TITLE
KeePass not closeable when updating KeePass

### ISSUE THREAD

**Issue by marcelser** [Rookiestyle/EarlyUpdateCheck#56]
## Overview
When KeePass itself is updating you cannot close KeePass.

## Steps to Reproduce
1. select "Setuip" as installation type
2. use "Check for Updates" or wait for an automatic-check when a KeePass update is available
3. select to update KeePass
4. In the Popup it says "You have to close KeePass" but you cannot do this as KeePass is blocked from any input as long as the PopUp is showing. So clicking "Yes" actually fails. So the only workaround is to choose "No" and then first close KeePass manually and run setup.exe

## Expected Behavior
The plugin should either not block KeePass from beeing closed or even better close KeePass. For this the Plugin should tell something like "Choose 'Yes' for closing KeePass automatically (warning unsaved data maybe lost) or 'No' to open download directory"

## Actual Behavior
The plugin blocks the possibility to close down KeePass so the 'Yes' option is not working.

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 11
KeePass Version: 2.5.31
Plugin Version: 4.2.1

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
![image](https://user-images.githubusercontent.com/36454520/228628050-e64710cb-a434-4ee2-8bd6-09cf6810d2f0.png)
You refer to this popup, right?

The behaviour should be as follows (and my tests work as expected)
Clicking 'No' will close the popup and open the temp folder containing KeePass-2.53.1-Setup.exe
Clickinng 'Yes' will close the popup and start KeePass-2.53.1-Setup.exe

KeePass itself will not be closed in any of the above cases.

When you click 'Yes' the popup is closed but beside that nothing happens?

**Comment by Rookiestyle** [comment]
Closed because of no feedback.
I'll reopen this issue once feedback is given
