### ISSUE TITLE
Updates for ExternalPluginUpdates

### ISSUE THREAD

**Issue by caspadan** [Rookiestyle/EarlyUpdateCheck#66]
Good day Rookiestyle

Here are some additions for the ExternalPluginUpdates.xml file.
You may need to verify Dominik's plugins (KeeModifiedBy, OtpKeyProv, and KeeResize), as I was not able to get older versions to test.

```
<UpdateInfoExtern>
		<PluginName>AutoTypeShow</PluginName>
		<PluginURL>https://sourceforge.net/projects/autotypeshow/</PluginURL>
		<PluginUpdateURL>https://sourceforge.net/projects/autotypeshow/files/latest/download</PluginUpdateURL>
		<UpdateMode>ZipExtractPlgx</UpdateMode>
		<AllowVersionStripping>False</AllowVersionStripping>
	</UpdateInfoExtern>
	<UpdateInfoExtern>
		<PluginName>EditEntryGroup</PluginName>
		<PluginURL>https://sourceforge.net/projects/editentrygroup/</PluginURL>
		<PluginUpdateURL>https://sourceforge.net/projects/editentrygroup/files/latest/download</PluginUpdateURL>
		<UpdateMode>ZipExtractPlgx</UpdateMode>
		<AllowVersionStripping>False</AllowVersionStripping>
	</UpdateInfoExtern>
	<UpdateInfoExtern>
		<PluginName>KeeModifiedBy</PluginName>
		<PluginURL>https://keepass.info/plugins.html#keemodifiedby</PluginURL>
		<PluginUpdateURL>https://keepass.info/extensions/v2/keemodifiedby/KeeModifiedBy-{major}{.minor}{.build}.zip</PluginUpdateURL>
		<UpdateMode>ZipExtractPlgx</UpdateMode>
		<AllowVersionStripping>True</AllowVersionStripping>
	</UpdateInfoExtern>
	<UpdateInfoExtern>
		<PluginName>OtpKeyProv</PluginName>
		<PluginURL>https://keepass.info/plugins.html#otpkeyprov</PluginURL>
		<PluginUpdateURL>https://keepass.info/extensions/v2/otpkeyprov/OtpKeyProv-{major}{.minor}{.build}.zip</PluginUpdateURL>
		<UpdateMode>ZipExtractPlgx</UpdateMode>
		<AllowVersionStripping>True</AllowVersionStripping>
	</UpdateInfoExtern>
	<UpdateInfoExtern>
		<PluginName>TwoFactorQRCodeReader</PluginName>
		<PluginURL>https://sourceforge.net/projects/twofactorqrcodereader/</PluginURL>
		<PluginUpdateURL>https://sourceforge.net/projects/twofactorqrcodereader/files/latest/download</PluginUpdateURL>
		<UpdateMode>ZipExtractPlgx</UpdateMode>
		<AllowVersionStripping>False</AllowVersionStripping>
	</UpdateInfoExtern>
```

**I'm not sure how to go about KeeResize - this method is only for the plgx file. Whether
or not the other files are necessary (say if you have the full version perhaps), I'm not too clear.
Could use UpdateMode ZipExtractAll otherwise, but then you also get the readme file, which is not desired:**

	<UpdateInfoExtern>
		<PluginName>KeeResize</PluginName>
		<PluginURL>https://keepass.info/extensions/v2/keeresize/</PluginURL>
		<PluginUpdateURL>https://keepass.info/extensions/v2/keeresize/KeeResize-{major}{.minor}{.build}.zip</PluginUpdateURL>
		<UpdateMode>ZipExtractPlgx</UpdateMode>
		<AllowVersionStripping>True</AllowVersionStripping>
	</UpdateInfoExtern>

**Another tricky one, which is probably not possible, is NotesSearchPlugin. The download URL contains a hash, so the URL will change.. However, I'm putting it here in case you want to have a look or get ideas for other enhancements to the plugin:**

	<UpdateInfoExtern>
		<PluginName>NotesSearchPlugin</PluginName>
		<PluginURL>https://besch-it.com/keepass-notes-search-plugin-innerhalb-der-kommentare-suchen-search-within-notes-field/</PluginURL>
		<PluginUpdateURL>https://besch-it.com/sdc_download/923/?key=6y3ck8c6hn2dmdl38d6nd6bnzkihvb</PluginUpdateURL>  
		<UpdateMode>ZipExtractPlgx</UpdateMode>
		<AllowVersionStripping>False</AllowVersionStripping>
	</UpdateInfoExtern>

Kind regards

**Comment by Rookiestyle** [comment]
NotesSearchPlugin won't work, I'll add the rest. Thanks a lot!
