### ISSUE TITLE
插件更新

### ISSUE THREAD

**Issue by 2022414** [Rookiestyle/EarlyUpdateCheck#67]
keepass便携式，插件文件夹已经更名成Plugins，不再是Portable，导致插件更新功能无法正常使用，希望作者更新一下

The KeePass portable version's plugin folder has been renamed to "Plugins," no longer "Portable," which has caused the plugin update feature to malfunction. I hope the author can update it.

![image_17](https://github.com/user-attachments/assets/f03e9e04-afa0-47f8-b703-a7fed26357f4)
![image_18](https://github.com/user-attachments/assets/925e1113-f0c2-4a82-a1a2-7190329be51e)

**Comment by Rookiestyle** [comment]
"Portable" referee to the way you install KeePass.
For all three cases (Portable, Setup, MSI) the folder for plugins is always named "Plugins".

What exactly is not working?

**Comment by 2022414** [comment]
> “便携”是指您安装 KeePass 的方式。对于所有三种情况（Portable、Setup、MSI），插件的文件夹始终命名为“Plugins”。
> 
> 究竟是什么不起作用？哪个插件不能更新？请激活调试模式，重试并在此处上传调试文件。细节： https://github.com/Rookiestyle/EarlyUpdateCheck/wiki/Create-a-debugfile

I'm not exactly clear on the specific reasons, as I don't understand programming, but I still appreciate your response and development.

具体是什么原因我并不清楚，我不懂编程，不过还是感谢您的恢复和开发

**Comment by Rookiestyle** [comment]
I'm not sure how to interpret your last reply.


You wrote:
> The KeePass portable version's plugin folder has been renamed to "Plugins," no longer "Portable," which has caused the plugin update feature to ** malfunction**. I hope the author can update it.

There is no malfunction as far as I can tell.

Do you face a malfunction?
If yes: What exactly does not work and which plugin cannot be updated?
