### ISSUE TITLE
possibility to go directly to the changelog 

### ISSUE THREAD

**Issue by alexis26** [Rookiestyle/EarlyUpdateCheck#7]
hi,
in the update check window, it would be very convenient to be able to go directly to the version changes (or at least on the release page which usually contains a summary).

(I don't know exactly how it works, but as Keepass know where to download the latest version, it should be able to display this page...)

-it could be by clicking on (each) plugin - for the moment this click send to the https://keepass.info/plugins.html page, which makes it duplicate with the link at the bottom...
-or by adding a column on the info of this window with a link or a clickable button...

Merci

**Comment by Rookiestyle** [comment]
KeePass does not know where to download plugins.
EarlyUpdateCheck knows where to download updates for my plugins.

I am already working on something like this.
Changing the doubleclick behaviour isn't easily possible, this is predefined by KeePass and I don't plan to add one more button to the screen either.
Instead, I'm working on adding a *Go to release page* context menu to my plugins shown in the update check window

**Comment by Rookiestyle** [comment]
I found a way to change doubleclick behaviour and display a contextmenu only if this does not succeed as a fallback.

**Comment by alexis26** [comment]
hi,
Waow, I didn't have time to answer you in the WE and it's already up to date and working this morning ... wonderful ! 

I know that EarlyUpdateCheck only monitors 'your extensions', but wouldn't it be possible to do the same (just double-click the browser) with the others by manually entering the URL of our choice in a customizable EarlyUpdateCheck menu for each one?

but thank you already for that
