### ISSUE TITLE
WebAutoType Update Check Failed

### ISSUE THREAD

**Issue by r13s** [Rookiestyle/EarlyUpdateCheck#9]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)
An error occurred while checking the version of the WebAutoType plugin.

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Open KeePass.
2. Click Help → Check for Updates.
3. In the Update Check window, see an error for WebAutoType “Update check failed. Version information file cannot be downloaded.”

![1-1607006798](https://user-images.githubusercontent.com/13751556/101045350-450de280-3591-11eb-9cd5-5601a9c496d9.png)

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)
Plugin updates should be checked with no errors.

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)
Error for WebAutoType “Update check failed. Version information file cannot be downloaded.”

Here is my ExternalPluginUpdates.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<UpdateInfoExternList>
  <UpdateInfoExtern>
    <PluginName>KeePassQuickUnlock</PluginName>
    <PluginURL>https://github.com/JanisEst/KeePassQuickUnlock/releases</PluginURL>
    <PluginUpdateURL>https://github.com/JanisEst/KeePassQuickUnlock/releases/latest/download/KeePassQuickUnlock.plgx</PluginUpdateURL>
    <UpdateMode>PlgxDirect</UpdateMode>
    <AllowVersionStripping>True</AllowVersionStripping>
  </UpdateInfoExtern>
  <UpdateInfoExtern>
    <PluginName>Yet Another Favicon Downloader</PluginName>
    <PluginURL>https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases</PluginURL>
    <PluginUpdateURL>https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/latest/download/YetAnotherFaviconDownloader.plgx</PluginUpdateURL>
    <UpdateMode>PlgxDirect</UpdateMode>
    <AllowVersionStripping>True</AllowVersionStripping>
  </UpdateInfoExtern>
  <UpdateInfoExtern>
    <PluginName>TCATO Placeholder</PluginName>
    <PluginURL>http://niki.hammler.net/wiki/KeePass#TCATO_Placeholder</PluginURL>
    <PluginUpdateURL>http://niki.hammler.net/w/images/d/de/TCATO_Placeholder_v{MAJOR}{.MINOR}{.BUILD}.zip</PluginUpdateURL>
    <UpdateMode>ZipExtractPlgx</UpdateMode>
    <AllowVersionStripping>True</AllowVersionStripping>
  </UpdateInfoExtern>
  <UpdateInfoExtern>
    <PluginName>WebAutoType</PluginName>
    <PluginURL>https://sourceforge.net/projects/webautotype/</PluginURL>
    <PluginUpdateURL>https://sourceforge.net/projects/webautotype/files/latest/download</PluginUpdateURL>
    <UpdateMode>ZipExtractPlgx</UpdateMode>
    <AllowVersionStripping>True</AllowVersionStripping>
  </UpdateInfoExtern>
</UpdateInfoExternList>
```

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 10 x64
KeePass Version: 2.46
Plugin Version: 3.1.1

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)
[Debug_EarlyUpdateCheck_20201203T141435Z.zip](https://github.com/Rookiestyle/EarlyUpdateCheck/files/5636936/Debug_EarlyUpdateCheck_20201203T141435Z.zip)

**Comment by Rookiestyle** [comment]
EarlyUpdateCheck does not check for updates, it (re)acts based on the already existing update check that is part of standard KeePass.

KeePass can't check for updates of WebAutoType.
A solution can be found here: https://sourceforge.net/projects/webautotype/

> If integration with KeePass Check for Updates is required, install http://sourceforge.net/projects/kpsfupdatechecker

**Comment by r13s** [comment]
Oh, now I see, thanks. But this is not in the wiki, and I thought that your plugin has all the necessary functionality.
